sonar.projectKey=abhishekelsner_new-elsner
sonar.organization=abhishekelsner
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.exclusions=tests/**,test
sonar.coverage.exclusions=tests/**
sonar.php.coverage.reportPaths=reports/coverage.xml,coverage.xml

